name: Sync rules to main branch

on:
  schedule:
    - cron: '0 2 * * 1'  # 每周一 UTC 2 点执行（北京时间每周一上午 10 点）
  workflow_dispatch:

permissions:
  contents: write  # 显式授权推送权限

jobs:
  sync-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main  # 始终操作 main 分支（即便它不是默认分支）
          persist-credentials: true

      - name: Create Rule directory if not exists
        run: mkdir -p Rule

      - name: Download cncidr.txt (no modification)
        run: |
          curl -s https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/cncidr.txt \
          -o Rule/cncidr.txt

      - name: Download tld-not-cn.txt (no modification)
        run: |
          curl -s https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/tld-not-cn.txt \
          -o Rule/tld-not-cn.txt

      - name: Download direct.txt (no modification)
        run: |
          curl -s https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/direct.txt \
          -o Rule/direct.txt

      - name: Commit and push all rule files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Rule/cncidr.txt Rule/tld-not-cn.txt Rule/direct.txt
          git commit -m "Auto sync rule files (no modification)" || echo "No changes to commit"
          git push origin main
